### ISSUE TITLE
Lab2

### ISSUE THREAD

**Issue by fantkolja** [Chipernes/Design-Patterns#2]
- [this implementation](https://github.com/Chipernes/Design-Patterns/blob/main/lab-2/src/Task-2-Abstract-factory/factories/DeviceFactory.ts#L4-L7) is a bit non-conventional. It would be closer to the textbook sample to have separate interfaces for each separate Device (ILaptop, IEBook etc), so each method returns its interface. And then you would have e.g. a BalaxyLaptop class which implements Ilaptop etc.
- It's not a [Singleton](https://github.com/Chipernes/Design-Patterns/blob/main/lab-2/src/Task-3-Singleton/Authenticator.ts) implementation, please check the lecture [example](https://github.com/fantkolja/design-patterns-samples/blob/master/csharp/src/patterns/Singleton/Singleton.cs#L3-L19)

**Comment by Chipernes** [comment]
So, should I rewrite those mistakes, I've made to get a mark? Because I
don't have one for this laboratory work.
[image: image.png]

**Comment by Chipernes** [comment]
So, should I rewrite those mistakes, I've made to get a mark? Because I don't have one for this laboratory work.

![image](https://github.com/Chipernes/Design-Patterns/assets/105077070/0a5fa520-7bbf-44d7-8268-e6a189732534)

**Comment by fantkolja** [comment]
Sorry, forgot to write your grade.
There is no need to fix those mistakes unless by the end of the course, we get a vague result (e.g. 88)
